apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lesd2rwyk-python 
  janus-idp.io/tekton: lesd2rwyk-python
  backstage.io/kubernetes-id: lesd2rwyk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lesd2rwyk-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  