apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lesd2rwyk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lesd2rwyk-python 
  name: lesd2rwyk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lesd2rwyk-python 
